### ISSUE TITLE
[문의] SessionId 를 FunMessage 형 sid 변수에 넣을 때

### ISSUE THREAD

**Issue by say2elgar** [iFunFactory/engine-plugin-unity3d#1]
타입 캐스팅 오류가 납니다.
byte[] 를 string 을 바꿔야 할 거 같습니다.

**Comment by junhyun-ifunfactory** [comment]
서버 버전이 낮아서 최신 플러그인과 호환이 되지 않는걸로 보입니다.
플러그인 버전 190 이상은 서버 버전 1945-stable 이상이 필요 하며 Protobuf DLL을 새로 빌드해야 할 수도 있습니다.
감사합니다.
